server{
 listen 80 default_server;
 listen [::]:80 default_server;

 index index.html;

 server_name local.portfolio.com;
 client_max_body_size 2M;

 charset utf-8;

 root /var/www/html/public;

 location / {
         try_files $uri $uri/ /index.html;
     }

  location ~ /\.ht {
         deny  all;
  }
}